import type { Metadata } from "next";
import { Montserrat } from "next/font/google";

import NavBar from "@/components/NavBar";

import classNames from "classnames";
import "./globals.css";

const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "My Portfolio",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    const bodyClasses = classNames(montserrat.className, "px-32");
    return (
        <html lang="en">
            <body className={bodyClasses}>
                <NavBar />
                {children}
            </body>
        </html>
    );
}
